# The help comments are Based on https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html

# Include shared color definitions
include ../utils/colors.mk
include ../utils/common.mk

.DEFAULT_GOAL := help

.PHONY: build test

build: ## build the sample client
	@printf "Running $(C_YELLOW)build...$(T_RESET)\n"
	@printf "🚧 Sample $(C_RED)client is not finished$(T_RESET) yet...\n"

test: ## run tests for the sample client
	@printf "Running $(C_YELLOW)tests...$(T_RESET)\n"
	@printf "🚧 Sample $(C_RED)client is not finished$(T_RESET) yet...\n"
